Update message
kartoza/sawps pull request #1140
Opened 2023-09-28 11:52 UTC by Fanevanjanahary

2023-09-28 12:15 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 23 min

2023-09-29 07:21 UTC, dimasciput requested changes

2023-09-29 07:21 UTC, dimasciput commented on django_project/frontend/src/containers/MainPage/Upload/SpeciesUploader.tsx
> +                        console.log(response.data)
Please remove this

2023-09-29 07:21 UTC, dimasciput commented on django_project/frontend/src/containers/MainPage/Upload/SpeciesUploader.tsx
> +                    wait(5000).then(r =>
Why do we need to wait for 5 seconds?

2023-10-03 07:45 UTC, dimasciput approved these changes

2023-10-03 07:45 UTC, merged

2023-10-03 07:52 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 19 min

2023-10-03 07:54 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 1 min 16 sec

2023-10-03 08:14 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 38 sec