Added docs on testing section
kartoza/sawps pull request #1153
Opened 2023-10-01 02:40 UTC by osundwajeff

@timlinux  I have added the `Testing` section to the docs as you had suggested. Kindly check it out.

![2023-10-01_05-36](https://github.com/kartoza/sawps/assets/49160399/aa99e747-9d9e-4ecb-a038-de5289028c53)

2023-10-01 02:53 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 13 min

2023-10-02 07:01 UTC, Jeremy-Prior requested changes
Minor spelling changes and then changes to img names.

Nice work on updating the guide/index and the nav section correctly.

2023-10-02 07:51 UTC, osundwajeff commented on docs/src/developer/guide/testing.md
> +![push or pull request](./img/testing-ci-gh-actions.png)
Alright. I'll correct those ones @Jeremy-Prior

2023-10-03 07:08 UTC, osundwajeff commented on docs/src/developer/guide/testing.md
> +This command will install all the required browsers and other dependencies. The [directory stucture](https://playwright.dev/docs/intro#whats-installed) will be as follows:
Done.

2023-10-03 07:08 UTC, osundwajeff commented on docs/src/developer/guide/index.md
> +* **[Testing:](./testing.md)** This section focuses on setting up end to end testing for the project.
Done.

2023-10-03 07:09 UTC, osundwajeff commented on docs/src/developer/guide/testing.md
> +![push or pull request](./img/testing-ci-gh-actions.png)
Done.

2023-10-03 07:16 UTC, Jeremy-Prior approved these changes

2023-10-03 07:32 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 29 min

2023-10-04 01:23 UTC, merged

2023-10-04 01:25 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 45 sec