Fix repeating reports data
kartoza/sawps pull request #1183
Opened 2023-10-04 10:53 UTC by ketankartoza

This PR is for the issue #1174 #1182

Before:-
![image](https://github.com/kartoza/sawps/assets/138113337/20a0e849-c861-4ba0-a440-cfe6d9f74b65)

After:-
![image](https://github.com/kartoza/sawps/assets/138113337/1acbbe43-aa98-46ff-9f41-42f1ecce2658)
![image](https://github.com/kartoza/sawps/assets/138113337/ee1ad052-57c0-4b3d-bad2-8cfbfd76b887)

2023-10-06 01:36 UTC, dimasciput requested changes

2023-10-06 01:36 UTC, dimasciput commented on django_project/frontend/src/containers/MainPage/Data/index.tsx
> +                                headerName: key.replace("owned_species__", "").replace("taxon", "").replace("varbatim", "").split('_')
can you change to serializer instead in the backend, so it will get a proper title

2023-10-06 11:08 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 16 min

2023-10-06 11:20 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 43 sec

2023-10-09 01:37 UTC, merged

2023-10-09 01:42 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 4 min 40 sec