fixed issues for selection input position
kartoza/sawps pull request #1245
Opened 2023-10-10 09:34 UTC by ketankartoza

This PR for #1243 #1230 

Fixed selection input position,
And added clear button for clear 

Before:
<img width="336" alt="Screenshot 2023-10-10 at 2 59 47 PM" src="https://github.com/kartoza/sawps/assets/138113337/0eff5d62-e3b3-4820-ac99-2ef63713a1b6">
After:
<img width="404" alt="Screenshot 2023-10-10 at 2 58 29 PM" src="https://github.com/kartoza/sawps/assets/138113337/3517da50-8a85-4da5-97dd-78ec161321ce">

2023-10-10 09:52 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 17 min

2023-10-11 05:25 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 13 min

2023-10-12 02:47 UTC, dimasciput requested changes
Please also fix the conflicts

2023-10-12 02:47 UTC, dimasciput commented on django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
> +    const ClearFilter = () => {
```suggestion
    const clearFilter = () => {
```

2023-10-12 02:47 UTC, dimasciput commented on django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
> +                    <div className='clear-button'><Typography color='#75B37A' className='pointer' fontSize='medium' onClick={ClearFilter}>Clear</Typography></div>
```suggestion
                    <div className='clear-button'><Typography color='#75B37A' className='pointer' fontSize='medium' onClick={clearFilter}>Clear</Typography></div>
```

2023-10-18 01:23 UTC, dimasciput commented
The filter was updated with another PR

2023-10-18 01:23 UTC, closed without merging

2023-10-18 01:38 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 41 sec