Documentation for login page
kartoza/sawps pull request #1262
Opened 2023-10-11 06:19 UTC by ketankartoza

This PR is for issue #1257

2023-10-11 06:21 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 38 sec

2023-10-11 06:44 UTC, Jeremy-Prior requested changes
Minor changes requested. Good job

2023-10-11 06:44 UTC, Jeremy-Prior commented on docs/src/user/manual/login-logout/login-page.md
> +## Remember Me
```suggestion
### Remember Me
```

2023-10-11 06:44 UTC, Jeremy-Prior commented on docs/src/user/manual/login-logout/login-page.md
> +## Security
```suggestion
### Security
```

2023-10-11 06:44 UTC, Jeremy-Prior commented on docs/src/user/manual/login-logout/login-page.md
> +## Logging In
```suggestion
### Logging In
```

2023-10-11 06:44 UTC, Jeremy-Prior commented on docs/src/user/manual/login-logout/login-page.md
> +4. **Login Button**: Click the "LOGIN" button to submit your credentials and access your account.
```suggestion
4. **Login Button**: Click the `LOGIN` button to submit your credentials and access your account.
```

2023-10-11 06:44 UTC, Jeremy-Prior commented on docs/src/user/manual/login-logout/login-page.md
> +Please ensure that you enter your email and password correctly to access your account. After clicking the "LOGIN" button, you will be redirected to two factor authentication page within the applicati
```suggestion
Please ensure that you enter your email and password correctly to access your account. After clicking the `LOGIN` button, you will be redirected to the two factor authentication page within the application.
```

2023-10-11 06:44 UTC, Jeremy-Prior commented on docs/src/user/manual/login-logout/login-page.md
> +
Please add a `## Summary` title above the summary here.

2023-10-11 07:19 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 6 sec

2023-10-12 06:27 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 25 min

2023-10-12 06:37 UTC, Jeremy-Prior approved these changes

2023-10-13 10:42 UTC, merged

2023-10-13 11:18 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 45 sec