Documentation for login 2fa page
kartoza/sawps pull request #1267
Opened 2023-10-11 08:57 UTC by ketankartoza

This PR is for issue #1260.

2023-10-11 12:13 UTC, Jeremy-Prior requested changes
Minor changes needed.

2023-10-11 12:13 UTC, Jeremy-Prior commented on docs/src/user/manual/login-logout/login-2fa-page
The file needs a .md suffix otherwise it won't build into the docs correctly.

e.g. login-2fa-page.md

2023-10-11 12:13 UTC, Jeremy-Prior commented on docs/src/user/manual/login-logout/login-2fa-page
> +The Two-Factor Authentication (2FA) Page is a critical security feature that adds an extra layer of protection to your account. With 2FA, you'll be required to enter a OTP (One-Time Password) code in
This is for the manual and not for the guide, so maybe we can reword this:
```suggestion
The Two-Factor Authentication (2FA) Page is a critical security feature that adds an extra layer of protection to your account. With 2FA, you'll be required to enter a OTP (One-Time Password) code in addition to your regular login credentials. This documentation provides an explanation of the 2FA page.
```

2023-10-11 12:13 UTC, Jeremy-Prior commented on docs/src/user/manual/login-logout/login-2fa-page
> +1. **OTP Code**: In the center of the page, you will find the OTP Code field. This is where you must enter the one-time password generated by your authentication app (Google Authenticator).
We should explain this acronym
```suggestion
1. **OTP Code**: In the centre of the page, you will find the OTP (One Time Pin) Code field. This is where you must enter the one-time password generated by your authentication app (Google Authenticator).
```

2023-10-11 12:13 UTC, Jeremy-Prior commented on docs/src/user/manual/login-logout/login-2fa-page
> +3. **Lost Your Device?**: Below the `Authenticate` button, you will see a section titled `Lost your device?` This section provides guidance for users who have lost access to their 2FA device. If you
```suggestion
3. **Lost Your Device?**: Below the `Authenticate` button, you will see a section titled `Lost your device?`. This section provides guidance for users who have lost access to their 2FA device. If you no longer have access to your authentication app, you can follow the instructions provided here to regain access to your account. Typically, this involves contacting your account administrator, or support, for further assistance.
```

2023-10-12 07:23 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 3 sec

2023-10-12 07:40 UTC, Jeremy-Prior approved these changes
LGTM

2023-10-13 10:42 UTC, merged

2023-10-13 11:16 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 47 sec