Update help page documentation
kartoza/sawps pull request #1272
Opened 2023-10-11 13:35 UTC by ketankartoza

This PR is for the updates on the help page and the contact page.

2023-10-11 13:38 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 0 sec

2023-10-12 07:43 UTC, Jeremy-Prior requested changes
Minor heading level changes

2023-10-12 07:43 UTC, Jeremy-Prior commented on docs/src/user/manual/help-contact.md
> +# Contact Page Documentation
```suggestion
## Contact Page
```

2023-10-12 07:43 UTC, Jeremy-Prior commented on docs/src/user/manual/help-contact.md
> +## Description
```suggestion
### Description
```

2023-10-12 07:43 UTC, Jeremy-Prior commented on docs/src/user/manual/help-contact.md
> +## Contact Form
```suggestion
### Contact Form
```

2023-10-13 10:40 UTC, merged

2023-10-13 10:45 UTC, ketankartoza commented
Thanks @dimasciput

2023-10-13 10:57 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 17 min

2023-10-13 10:59 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 4 sec

2023-10-13 11:01 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 49 sec

2023-10-13 11:12 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 10 min