Population trend graph
kartoza/sawps pull request #1309
Opened 2023-10-16 14:25 UTC by tinashechiraya

Description:

I have added a line chart similar to the one on the dashboard but this one is also
configured to display as points (dots) with a specified size and color.
With this the chart has dots representing the actual counts per year on the chart,
in addition to the existing trend line and confidence intervals.

On local host I don't have the permissions to get the data but the implementation is the same as the charts on the dashboard 
![image](https://github.com/kartoza/sawps/assets/70011086/82f135b8-f4ec-4fc7-967c-5d2f26d46555)

2023-10-17 00:03 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 55 sec

2023-10-17 01:33 UTC, dimasciput requested changes

2023-10-17 01:33 UTC, dimasciput commented on django_project/frontend/models/statistical.py
> +SPECIE_PER_PROPERTY = 'specie_per_property'
Species is both singular and plural

2023-10-17 01:33 UTC, dimasciput commented on django_project/frontend/api_views/statistical.py
> +        csv_data = [
please use serializer instead

2023-10-18 00:20 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 8 min 11 sec

2023-10-18 00:31 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 10 min

2023-10-18 00:42 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 10 min

2023-10-18 00:49 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 7 min 11 sec

2023-10-18 00:54 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 5 min 6 sec

2023-10-18 00:59 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 4 min 41 sec

2023-10-18 01:04 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 4 min 54 sec

2023-10-18 01:09 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 4 min 51 sec

2023-10-18 01:25 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 6 min 52 sec

2023-10-18 01:57 UTC, tinashechiraya commented
@dimasciput I have applied the changes

2023-10-18 04:45 UTC, merged

2023-10-18 04:53 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 46 sec