Documentation online form
kartoza/sawps pull request #1346
Opened 2023-10-18 12:13 UTC by ketankartoza

This PR is for issue #1287

2023-10-18 12:15 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 51 sec

2023-10-19 01:20 UTC, dimasciput commented
@Jeremy-Prior please review

2023-10-19 04:56 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 35 sec

2023-10-19 07:36 UTC, Jeremy-Prior requested changes

2023-10-19 07:36 UTC, Jeremy-Prior commented on docs/src/user/manual/data-upload/online-form.md
> +2. **Property detail**: Showing property details alog with the image.
```suggestion
2. **Property detail**: Showing property details along with the image.
```

2023-10-19 07:36 UTC, Jeremy-Prior commented on docs/src/user/manual/data-upload/online-form.md
> +    ##### Introduction/Reintroduction Table and Form
```suggestion
    **Introduction/Reintroduction Table and Form**
```

2023-10-19 07:36 UTC, Jeremy-Prior commented on docs/src/user/manual/data-upload/online-form.md
> +    10. **Founder Population**: Indicate whether the introduced or reintroduced group is considered a founder population. Use the radio buttons to select `Yes` or `No`. This is mendatory.
```suggestion
    10. **Founder Population**: Indicate whether the introduced or reintroduced group is considered a founder population. Use the radio buttons to select `Yes` or `No`. This is mandatory.
```

2023-10-19 07:36 UTC, Jeremy-Prior commented on docs/src/user/manual/data-upload/online-form.md
> +    11. **Event**: Select the appropriate event type from the dropdown menu. Choose the event category that best describes the introduction or reintroduction process. This field is mendatory.
```suggestion
    11. **Event**: Select the appropriate event type from the dropdown menu. Choose the event category that best describes the introduction or reintroduction process. This field is mandatory.
```

2023-10-19 07:36 UTC, Jeremy-Prior commented on docs/src/user/manual/data-upload/online-form.md
> +    12. **Source**: Describe the source of the introduced or reintroduced population. This field is mendatory.
```suggestion
    12. **Source**: Describe the source of the introduced or reintroduced population. This field is mandatory.
```

2023-10-19 07:36 UTC, Jeremy-Prior commented on docs/src/user/manual/data-upload/online-form.md
> +    ##### Off-take Table and Form
```suggestion
    **Off-take Table and Form**
```

2023-10-19 07:36 UTC, Jeremy-Prior commented on docs/src/user/manual/data-upload/online-form.md
> +
```suggestion

```

2023-10-20 05:41 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 54 sec

2023-10-20 05:44 UTC, ketankartoza commented
@Jeremy-Prior I have done with all the suggested changes. Please review. Thanks

2023-10-20 06:56 UTC, Jeremy-Prior approved these changes
LGTM

2023-10-20 07:24 UTC, merged

2023-10-20 07:29 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 23 sec