Documentation about page
kartoza/sawps pull request #1410
Opened 2023-10-24 08:15 UTC by ketankartoza

This PR is for issue #1399 

Note: I have added a quick fix for the logos link.

2023-10-24 08:30 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 9 min 14 sec

2023-10-24 08:57 UTC, Jeremy-Prior requested changes

2023-10-24 08:57 UTC, Jeremy-Prior commented on docs/src/user/manual/about.md
> +![About Page](./img/about-page-1.png)
```suggestion
## About Page

![About Page](./img/about-page-1.png)
```

2023-10-24 08:57 UTC, Jeremy-Prior commented on docs/src/user/manual/about.md
> +    ### SANBI
```suggestion
    **SANBI**
```

2023-10-24 08:57 UTC, Jeremy-Prior commented on docs/src/user/manual/about.md
> +    ### IDS
```suggestion
    **IDS**
```

2023-10-24 08:57 UTC, Jeremy-Prior commented on docs/src/user/manual/about.md
> +2. **Additional Pages**: Usefull Pages links.
```suggestion
2. **Additional Pages**: Useful Pages links.
```

2023-10-24 08:57 UTC, Jeremy-Prior commented on docs/src/user/manual/about.md
> +    ### KARTOZA
```suggestion
    **KARTOZA**
```

2023-10-24 11:20 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 5 sec

2023-10-24 11:43 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 22 sec

2023-10-25 05:30 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 8 min 36 sec

2023-10-27 01:39 UTC, dimasciput commented
@Jeremy-Prior please review

2023-10-28 09:36 UTC, merged

2023-10-28 09:44 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 30 sec