Documentation for layers
kartoza/sawps pull request #1435
Opened 2023-10-25 14:02 UTC by ketankartoza

This PR is for the issue #1417 

https://github.com/kartoza/sawps/assets/138113337/f5228704-1251-417d-af1d-0fbbfe38cadc

2023-10-25 14:05 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 36 sec

2023-10-26 05:55 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 38 sec

2023-11-01 05:33 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 9 min 9 sec

2023-11-01 06:53 UTC, Jeremy-Prior requested changes

2023-11-01 06:53 UTC, Jeremy-Prior commented on docs/src/user/manual/explore/layers.md
> +Welcome to the documentation for map layers avalable in application. This document provides an overview of the map layers, how to access them, and how to interact with and customise their appearance.
```suggestion
Welcome to the documentation for map layers available in application. This document provides an overview of the map layers, how to access them, and how to interact with and customise their appearance.
```

2023-11-01 06:53 UTC, Jeremy-Prior commented on docs/src/user/manual/explore/layers.md
> +# Layers with map
```suggestion
## Map layers
```

2023-11-01 06:53 UTC, Jeremy-Prior commented on docs/src/user/manual/explore/layers.md
> +# Summary
```suggestion
## Summary
```

2023-11-01 07:01 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 25 sec

2023-11-01 07:03 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 42 sec

2023-11-03 00:58 UTC, merged

2023-11-03 01:07 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 37 sec