Documentation for 2FA
kartoza/sawps pull request #1482
Opened 2023-10-30 10:15 UTC by ketankartoza

This PR is for issue #1457

2023-11-03 12:01 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 6 sec

2023-11-08 12:19 UTC, Jeremy-Prior requested changes

2023-11-08 12:19 UTC, Jeremy-Prior commented on docs/src/user/manual/register/setup-2fa.md
> +4. **VERIFY**: User can verify token using the `VERIFY` button. Upon successful verification, Two-Factor Authentication will be enabled for SAWPS account.
```suggestion
4. **VERIFY**: Users can verify the token using the `VERIFY` button. Upon successful verification, Two-Factor Authentication will be enabled for SAWPS account and the user will be redirected to continue registering.
```

2023-11-08 12:19 UTC, Jeremy-Prior commented on docs/src/user/manual/register/setup-2fa.md
> +2. **Two-factor authentication devices**: Two-factor authentication devices table displays names of devices and delete icon to delete the specific device.
```suggestion
2. **Two-factor authentication devices**: The two-factor authentication devices table displays the names of devices and the delete icon to delete the specific device.
```

2023-11-08 12:19 UTC, Jeremy-Prior commented on docs/src/user/manual/register/setup-2fa.md
> +    2. **Delete Icon**: User can delete the specific device by clicking on the delete icon.
```suggestion
    2. **Delete Icon**: Users can delete the specific device by clicking on the delete icon.
```

2023-11-08 12:19 UTC, Jeremy-Prior commented on docs/src/user/manual/register/setup-2fa.md
> +        By clicking on the delete icon user will see popup for device delete confirmation.
```suggestion
        By clicking on the delete icon users will see popup for confirming the deletion of a device.
```

2023-11-08 12:19 UTC, Jeremy-Prior commented on docs/src/user/manual/register/setup-2fa.md
> +        2. **Delete**: `DELETE` button to delete device.
```suggestion
        1. The `CANCEL` button is used to cancel the device deletion.

        2. The `DELETE` button is used to delete the device.
```

2023-11-08 12:19 UTC, Jeremy-Prior commented on docs/src/user/manual/register/setup-2fa.md
> +3. **Add Device**: `ADD DEVICE` button to add new device. By clicking on the `ADD DEVICE` button user will see the popup to add new device.
```suggestion
3. Click on the `ADD DEVICE` button to add a new device. By clicking on the button users will see the popup to add new device.
```

2023-11-08 12:19 UTC, Jeremy-Prior commented on docs/src/user/manual/register/setup-2fa.md
> +    1. **Device Name**: Input field to insert device name.
```suggestion
    1. **Device Name**: Input field to add device name.
```

2023-11-08 12:19 UTC, Jeremy-Prior commented on docs/src/user/manual/register/setup-2fa.md
> +    3. **Cancel**: `CANCEL` button to cancel adding new device process.
```suggestion
    3. **Cancel**: `CANCEL` button to cancel the process of adding a new device.
```

2023-11-08 12:19 UTC, Jeremy-Prior commented on docs/src/user/manual/register/setup-2fa.md
> +        2. **Close**: `CLOSE` button to close the popup.
```suggestion
    2. *By clicking on the `ADD` button users will be shown a popup for scanning the QR code. Users can scan QR code to generate token for new added device.

        ![QR Scan](./img/setup-2fa-4.png)

        1. **QR Code**: to be scanned to generate a token.

        2. `CLOSE` button to close the popup.
```

2023-11-08 12:19 UTC, Jeremy-Prior commented on docs/src/user/manual/register/setup-2fa.md
> +5. **Generate Backup Tokens**: By clicking on the `GENERATE BACKUP TOKENS` button user can generate tokens.
```suggestion
5. **`GENERATE BACKUP TOKENS`**: By clicking on this button users can generate their recovery tokens.
```

2023-11-08 12:19 UTC, Jeremy-Prior commented on docs/src/user/manual/register/setup-2fa.md
> +6. **Profile**: The `PROFILE` navigation link navigates to the [profile page](../user-profile/profile-page.md).
```suggestion
6. The `PROFILE` navigation link navigates to the [profile page](../user-profile/profile-page.md).
```

2023-11-08 12:19 UTC, Jeremy-Prior commented on docs/src/user/manual/register/setup-2fa.md
> +7. **Reminders**: The `REMINDERS` navigation link navigates to the [reminders page](../user-profile/reminders.md).
```suggestion
7. The `REMINDERS` navigation link navigates to the [reminders page](../user-profile/reminders.md).
```

2023-11-08 12:19 UTC, Jeremy-Prior commented on docs/src/user/manual/register/setup-2fa.md
> +8. **Notifications**:  The `NOTIFICATIONS` navigation link navigates to the [notification page](../user-profile/notifications.md).
```suggestion
8. The `NOTIFICATIONS` navigation link navigates to the [notification page](../user-profile/notifications.md).
```

2023-11-08 12:19 UTC, Jeremy-Prior commented on docs/src/user/manual/register/setup-2fa.md
> +9. **Organisations**: The `ORGANISATIONS` navigation link navigates to the [organisation page](../user-profile/organisation-page.md) for registered users.
```suggestion
9. The `ORGANISATIONS` navigation link navigates to the [organisation page](../user-profile/organisation-page.md) for registered users.
```

2023-11-08 12:19 UTC, Jeremy-Prior commented on docs/src/user/manual/register/setup-2fa.md
> +From now on, when user log in to SAWPS account, user will be prompted to enter the six-digit token generated by user's authenticator app in addition to user's regular login credentials. This extra la
```suggestion
When users log in to SAWPS account, they will be prompted to enter the six-digit token generated by the user's authenticator application in addition to their regular login credentials. This extra layer of security will help protect the user's account from unauthorized access.
```

2023-11-08 12:19 UTC, Jeremy-Prior commented on docs/src/user/manual/register/setup-2fa.md
> +Congratulations! You have successfully set up Two-Factor Authentication (2FA) for your SAWPS account, enhancing the security of your data and account. If you encounter any issues during the setup pro
```suggestion
If users encounter any issues during the setup process, they should reach out to the support team for assistance.
```

2023-11-09 05:29 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 40 sec

2023-11-09 08:13 UTC, Jeremy-Prior commented on docs/src/user/manual/register/setup-2fa.md
> +# Two-Factor Authentication (2FA) Setup Guide
```suggestion
# Two-Factor Authentication (2FA) Setup Page
```

2023-11-09 08:14 UTC, Jeremy-Prior commented on docs/src/user/manual/register/setup-2fa.md
> +# Two-Factor Authentication (2FA) Once Verify
```suggestion
# Two-Factor Authentication (2FA) Once Verified
```

2023-11-09 08:15 UTC, Jeremy-Prior commented on docs/src/user/manual/register/setup-2fa.md
> +Once users have successfully verified the 2FA, they will able to add device, delete device and generate backup tokens.
```suggestion
Once users have successfully verified the 2FA, they will be able to add device, delete device and generate backup tokens.
```

2023-11-09 08:18 UTC, Jeremy-Prior commented on docs/src/user/manual/register/setup-2fa.md
> +    2. *By clicking on the `ADD` button users will be shown a popup for scanning the QR code. Users can scan QR code to generate token for new added device.
```suggestion
    2. *By clicking on the `ADD` button users will be shown a popup for scanning the QR code. Users can scan the QR code to generate a token for a newly added device.
```

2023-11-09 08:20 UTC, Jeremy-Prior commented on docs/src/user/manual/register/setup-2fa.md
> +When users log in to SAWPS account, they will be prompted to enter the six-digit token generated by the user's authenticator application in addition to their regular login credentials. This extra lay
```suggestion
When users log in to their SAWPS account, they will be prompted to enter the six-digit token generated by the user's authenticator application in addition to their regular login credentials. This extra layer of security will help protect the user's account from unauthorized access.
```

2023-11-09 08:27 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 54 sec

2023-11-09 09:35 UTC, Jeremy-Prior approved these changes
LGTM

2023-11-09 09:36 UTC, Jeremy-Prior commented
@dimasciput please merge

2023-11-09 12:40 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 55 sec

2023-11-09 23:47 UTC, merged

2023-11-10 00:04 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 31 sec