Standardised docs
kartoza/sawps pull request #1499
Opened 2023-11-02 07:52 UTC by ketankartoza

This PR is for the issue #1412

2023-11-03 05:28 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 55 sec

2023-11-03 08:27 UTC, Jeremy-Prior requested changes

2023-11-03 08:27 UTC, Jeremy-Prior commented on docs/src/user/manual/login-logout/login-page.md
> +4. **Login Button**: Click the `LOGIN` button to submit the users credentials and access the users account.
```suggestion
4. **Login Button**: Click the `LOGIN` button to submit the user's credentials and access their account.
```

2023-11-03 08:27 UTC, Jeremy-Prior commented on docs/src/user/manual/login-logout/login-page.md
>  ### Remember Me
```suggestion
5. **Forgot Password**: The `Forgot Password` link opens the [forgot password](forgot-password.md) for reset password.

### Remember Me
```

2023-11-03 08:27 UTC, Jeremy-Prior commented on docs/src/user/manual/login-logout/login-page.md
> +The `Remember Me` checkbox allows the user to opt for the application to remember the users login information. When checked, the user won't need to re-enter the users email and password each time the
```suggestion
The `Remember Me` checkbox allows users to opt for the application to remember the users login information. When checked, users won't need to re-enter their email and password each time they visit the login page. This is particularly convenient for returning users who want a seamless login experience.
```

2023-11-03 08:27 UTC, Jeremy-Prior commented on docs/src/user/manual/login-logout/login-page.md
> +The `Login Page` is designed with security in mind to protect the users account and sensitive information. It uses encryption protocols and best practices to ensure that the users login credentials a
```suggestion
The `Login Page` is designed with security in mind to protect user accounts and sensitive information. It uses encryption protocols and best practices to ensure that users' login credentials are kept secure.
```

2023-11-03 08:27 UTC, Jeremy-Prior commented on docs/src/user/manual/login-logout/login-page.md
> +Please ensure that the user enter the users email and password correctly to access the users account. After clicking the `LOGIN` button, the user will be redirected to the two factor authentication p
```suggestion
Please ensure that users enter their email and password correctly to access their account. After clicking the `LOGIN` button, users will be redirected to the two factor authentication page within the application.
```

2023-11-03 08:27 UTC, Jeremy-Prior commented on docs/src/user/manual/login-logout/login-page.md
> +The Login Page serves as the gateway to the users account, providing a secure and user-friendly way to access the application's features and functionality.
```suggestion
The Login Page serves as the gateway to users' accounts, providing a secure and user-friendly way to access the application's features and functionality.
```

2023-11-03 08:27 UTC, Jeremy-Prior commented on docs/src/user/manual/login-logout/logout.md
> +The Logout Page is a secure and straightforward feature designed to allow users to log out of their account or session within the users application. This page provides a clean and intuitive interface
```suggestion
The Logout Page is a secure and straightforward feature designed to allow users to log out of their account or session within the users' application. This page provides a clean and intuitive interface for users to initiate the logout process, ensuring that their account remains protected and their session ends securely.
```

2023-11-03 08:27 UTC, Jeremy-Prior commented on docs/src/user/manual/login-logout/logout.md
> +1. **Logout Button**: To log out of the current the user session, click the `LOG OUT` button. This action will terminate the users session, ensuring they are securely logged out of the application.
```suggestion
1. **Logout Button**: To log out of the current user session, users should click the `LOG OUT` button. This action will terminate the user's session, ensuring they are securely logged out of the application.
```

2023-11-03 08:27 UTC, Jeremy-Prior commented on docs/src/user/manual/login-logout/logout.md
> +When the user click the `LOG OUT` button, the following actions occur:
```suggestion
When the user clicks on the `LOG OUT` button, the following actions occur:
```

2023-11-03 08:27 UTC, Jeremy-Prior commented on docs/src/user/manual/login-logout/logout.md
> +1. The system securely terminates the users current session.
```suggestion
1. The system securely terminates the user's current session.
```

2023-11-03 08:27 UTC, Jeremy-Prior commented on docs/src/user/manual/login-logout/logout.md
> +2. User will be logged out of the users account, and any temporary data related to the users session will be cleared.
```suggestion
2. The user will be logged out of their account, and any temporary data related to the user's session will be cleared.
```

2023-11-03 08:27 UTC, Jeremy-Prior commented on docs/src/user/manual/register/register-page.md
> +The Registration Page is a critical component of the platform, allowing users to create their accounts and gain access to the system. This page provides a straightforward and secure registration form
```suggestion
The Registration Page is a critical component of the platform, allowing users to create their accounts and gain access to the system. This page provides a straightforward and secure registration form for new users to sign up. It collects essential user information, including first name, last name, email address, password, and confirmation of the password.
```

2023-11-03 08:27 UTC, Jeremy-Prior commented on docs/src/user/manual/register/register-page.md
> +The Registration Form is designed to gather the necessary information for creating the user account.
```suggestion
The Registration Form is designed to gather the necessary information for creating a user account.
```

2023-11-03 08:27 UTC, Jeremy-Prior commented on docs/src/user/manual/register/register-page.md
> +1. **First Name**: Enter the users first name in this field. This is a required field and should contain the users legal first name.
```suggestion
1. **First Name**: Enter the user's first name in this field. This is a required field and should contain the user's legal first name.
```

2023-11-03 08:27 UTC, Jeremy-Prior commented on docs/src/user/manual/register/register-page.md
> +2. **Last Name**: Provide the users last name in this field. Similar to the first name, this is also a required field.
```suggestion
2. **Last Name**: Provide the user's last name in this field. Similar to the first name, this is also a required field.
```

2023-11-03 08:27 UTC, Jeremy-Prior commented on docs/src/user/manual/register/register-page.md
> +3. **Email Address**: Input the users valid email address. It must be a unique and valid email that the user have access to. This email will be used for communication and account recovery.
```suggestion
3. **Email Address**: Input the user's valid email address. It must be a unique and valid email that the user has access to. This email address will be used for communication and account recovery.
```

2023-11-03 08:27 UTC, Jeremy-Prior commented on docs/src/user/manual/register/register-page.md
> +4. **Password**: Create a strong and secure password for the users account. The users password should consist of a minimum of twelve characters, including at least one lowercase letter, one uppercase
```suggestion
4. **Password**: Create a strong and secure password for the user's account. Users' passwords should consist of a minimum of twelve characters, including at least one lowercase letter, one uppercase letter, one numeric character, and one special character.
```

2023-11-03 08:27 UTC, Jeremy-Prior commented on docs/src/user/manual/register/register-page.md
> +6. **Register Button**: Click this button to submit the registration form and create the users account.
```suggestion
6. **Register Button**: Click this button to submit the registration form and create the user's account.
```

2023-11-03 08:27 UTC, Jeremy-Prior commented on docs/src/user/manual/register/register-page.md
> +To ensure the security of the users account, we recommend the following password guidelines:
```suggestion
To ensure the security of the user's account, we recommend the following password guidelines:
```

2023-11-03 08:27 UTC, Jeremy-Prior commented on docs/src/user/manual/register/register-page.md
> +### Creating User Account
```suggestion
### Creating a User Account
```

2023-11-03 08:27 UTC, Jeremy-Prior commented on docs/src/user/manual/register/register-page.md
> +2. Double-check the users provided information to ensure accuracy, especially the users email and password.
```suggestion
2. Double-check the user's provided information to ensure accuracy, especially the user's email and password.
```

2023-11-03 08:27 UTC, Jeremy-Prior commented on docs/src/user/manual/register/register-page.md
> +After successfully registering, the user may receive an email confirmation to verify the users email address. Please follow the instructions in the email to complete the registration process.
```suggestion
After successfully registering, the user should receive an email confirmation to verify their email address. Please follow the instructions in the email to complete the registration process.
```

2023-11-03 08:27 UTC, Jeremy-Prior commented on docs/src/user/manual/register/register-page.md
> +We take the users security and privacy seriously. The users information is encrypted and stored securely, and we do not share the users personal data with third parties without the users consent.
```suggestion
We take user security and privacy seriously. User information is encrypted and stored securely, and we do not share the user's personal data with third parties without the user's consent.
```

2023-11-03 08:27 UTC, Jeremy-Prior commented on docs/src/user/manual/register/register-page.md
> +The Registration Page is the users gateway to becoming a registered user, providing the user with access to the platform's features and functionalities. If the user encounter any issues during the re
```suggestion
The Registration Page is the user's gateway to becoming a registered user, providing the user with access to the platform's features and functionalities. If the user encounters any issues during the registration process, they should contact the support team for assistance.
```

2023-11-03 08:27 UTC, Jeremy-Prior commented on docs/src/user/manual/user-profile/notifications.md
> +7. Pagination Link: The user is able to see the current page they are own. They are also able to navigate to previous and next pages using the nav links.
```suggestion
7. Pagination Link: The user is able to see the current page they are on. They are also able to navigate to previous and next pages using the navigation links.
```

2023-11-03 08:27 UTC, Jeremy-Prior commented on docs/src/user/manual/user-profile/reminders.md
> +8. **Pagination Link**: The user is able to see the current page they are own. They are also able to navigate to previous and next pages using the nav links.
```suggestion
8. **Pagination Link**: The user is able to see the current page they are on. They are also able to navigate to previous and next pages using the navigation links.
```

2023-11-03 08:27 UTC, Jeremy-Prior commented on docs/src/user/manual/user-profile/reminders.md
> +4. **Reminder Type**: Based on the user role within that specific organisation the user is able to specify if the reminder is for all organisation members or it is a personal reminder.
```suggestion
4. **Reminder Type**: Based on the user role within that specific organisation the user is able to specify if the reminder is for all organisation members or if it is a personal reminder.
```

2023-11-03 11:58 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 8 sec

2023-11-08 11:02 UTC, Jeremy-Prior requested changes

2023-11-08 11:41 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 14 sec

2023-11-08 12:03 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 54 sec

2023-11-10 05:23 UTC, ketankartoza commented
@Jeremy-Prior Please review this PR first because all other PRs rely on this PR.
Thanks!

2023-11-10 06:39 UTC, Jeremy-Prior requested changes

2023-11-10 06:39 UTC, Jeremy-Prior commented on docs/src/user/manual/login-logout/login-2fa-page.md
> +Two-Factor Authentication (2FA) is a critical security measure that significantly reduces the risk of unauthorized access to the user's account. It is highly recommended to enable and use 2FA to prot
```suggestion
Two-Factor Authentication (2FA) is a critical security measure that significantly reduces the risk of unauthorised access to the user's account. It is highly recommended to enable and use 2FA to protect a user's data and ensure the integrity of their account.
```

2023-11-10 07:16 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 45 sec

2023-11-10 07:22 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 32 sec

2023-11-10 07:41 UTC, Jeremy-Prior approved these changes
LGTM

2023-11-10 09:35 UTC, merged

2023-11-10 09:37 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 38 sec