Feature/1343 dynamic topper species icon
kartoza/sawps pull request #1529
Opened 2023-11-05 23:51 UTC by zamuzakki

This is PR for #1343 
[Kazam_screencast_00047.webm](https://github.com/kartoza/sawps/assets/7352963/5c198983-4dbb-4e2b-85af-82592c4f97b9)

2023-11-05 23:59 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 38 sec

2023-11-06 08:12 UTC, dimasciput requested changes

2023-11-06 08:12 UTC, dimasciput commented on django_project/species/models.py
> +        print(self.graph_icon)
@zamuzakki please remove this

2023-11-06 08:12 UTC, dimasciput commented on django_project/species/models.py
> +            topper_icon = graph_icon.replace(
Please update the code to use regex instead. Users should also be able to upload non-black svg files. Use this function :

```
def replace_fill_color(data, new_color):
    fill_pattern = re.compile(br'fill="[^"]*"', re.IGNORECASE)
    return fill_pattern.sub(br'fill="' + new_color.encode() + br'"', data)
```

2023-11-07 04:33 UTC, zamuzakki commented on django_project/species/models.py
> +        print(self.graph_icon)
I've removed this

2023-11-07 04:42 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 9 min 15 sec

2023-11-07 06:30 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 13 min

2023-11-07 06:43 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 12 min

2023-11-07 07:56 UTC, dimasciput approved these changes

2023-11-07 07:56 UTC, merged

2023-11-07 08:03 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 5 min 28 sec