Documentation user table admin
kartoza/sawps pull request #1539
Opened 2023-11-06 12:19 UTC by ketankartoza

This PR is for the issue #1510

2023-11-06 12:48 UTC, ketankartoza commented
@Jeremy-Prior This branch is made from the updated code of PR:- https://github.com/kartoza/sawps/pull/1507
So please approve and merge the above PR then ping me to rebase it with the main branch and then review.
Thanks!

2023-11-08 13:42 UTC, Jeremy-Prior requested changes
I provided many of these comments yesterday on another PR

2023-11-08 13:42 UTC, Jeremy-Prior commented on docs/src/administrator/manual/django-admin.md
> +    3. **New Password Confirmation**: Re-enter the new password in this field to confirm it. It should match the password entered in the `New Password` field.
```suggestion
    3. **New Password Confirmation**: Administrators should re-enter the new password in this field to confirm it. It should match the password entered in the `New Password` field.
```

2023-11-08 13:42 UTC, Jeremy-Prior commented on docs/src/administrator/manual/django-admin.md
> +After successfully changing the password, the user will receive a confirmation message indicating that the password has been updated.
```suggestion
After successfully changing the password, the administrator will receive a confirmation message indicating that the password has been updated.
```

2023-11-08 13:42 UTC, Jeremy-Prior commented on docs/src/administrator/manual/django-admin.md
> +5. **Recent Actions**: The `Recent Actions` section is typically located on the right side of the admin panel and provides a list of recent actions that have been performed within the admin interface
```suggestion
5. **Recent Actions**: The `Recent Actions` section is typically located on the right side of the administration panel and provides a list of recent actions that have been performed within the administration interface. These actions may include additions, deletions, or changes to data in the project. Clicking on any of the available links will take an administrator to the detail of recent action.
```

2023-11-08 13:42 UTC, Jeremy-Prior commented on docs/src/administrator/manual/django-admin.md
> +6. **Site Administration**: Site Administration this section provides links to various models and apps registered with the admin panel. It serves as the primary navigation point for managing a projec
```suggestion
6. **Site Administration**: This section provides links to various models and apps registered with the admin panel. It serves as the primary navigation point for managing a project's data. Clicking on any of the available links will take an administrator to the respective model's management page.
```

2023-11-08 13:42 UTC, Jeremy-Prior commented on docs/src/administrator/manual/django-admin.md
> +7. **Add**: This button is used to create a new item of the associated model. Clicking on `Add` link will open a form where users can enter the details of the new record.
```suggestion
7. **Add**: This button is used to create a new item of the associated model. Clicking on the `Add` link will open a form where administrators can enter the details of the new record.
```

2023-11-08 13:42 UTC, Jeremy-Prior commented on docs/src/administrator/manual/django-admin.md
> +8. **Change**: This button is used to edit an existing item from the list. When users click the `Change` button, they will be redirected to a page where they can see all the associate data of that mo
```suggestion
8. **Change**: This button is used to edit an existing item from the list. When administrators click the `Change` button, they will be redirected to a page where they can see all the associate data of that model and can select data to change.
```

2023-11-08 13:42 UTC, Jeremy-Prior commented on docs/src/administrator/manual/django-admin.md
> +* **Table**: To see data in a table, click on the table name.
Remove this line

2023-11-08 13:42 UTC, Jeremy-Prior commented on docs/src/administrator/manual/django-admin.md
> +1. **Table Name**: Clicking on the table name will allow users to see the table name.
```suggestion
1. **Table Name**: Clicking on the table name will allow administrators to see the table name.
```

2023-11-08 13:42 UTC, Jeremy-Prior commented on docs/src/administrator/manual/django-admin.md
> +* For more information, click on the [table](django-table.md) to see the tables documentation
```suggestion
* For more information, click [here](django-table.md) to see the tables documentation
```

2023-11-08 13:42 UTC, Jeremy-Prior commented on docs/src/administrator/manual/django-admin.md
> +* For more information, click on the [add](django-add-data.md) to see how to add a new data.
```suggestion
* For more information, click [here](django-add-data.md) to see how to add a new data.
```

2023-11-08 13:42 UTC, Jeremy-Prior commented on docs/src/administrator/manual/django-admin.md
> +* For more information, click on the [edit](django-change-data.md) to see how to edit data.
```suggestion
* For more information, click [here](django-change-data.md) to see how to edit data.
```

2023-11-08 13:42 UTC, Jeremy-Prior commented on docs/src/administrator/manual/django-change-data.md
> +1. **Form fields**: Form where users can input values for their record.
```suggestion
1. **Form fields**: Form where administrators can input values for their record.
```

2023-11-08 13:42 UTC, Jeremy-Prior commented on docs/src/administrator/manual/django-change-data.md
> +2. **Delete button**: Delete currently opened record. It will take users to confirmation page.
```suggestion
2. **Delete button**: Delete the currently opened record. It will take administrators to a confirmation page.
```

2023-11-08 13:42 UTC, Jeremy-Prior commented on docs/src/administrator/manual/django-change-data.md
> +    1. **Detail**: Detail about the object.
```suggestion
    1. **Detail**: Details about the object.
```

2023-11-08 13:42 UTC, Jeremy-Prior commented on docs/src/administrator/manual/django-change-data.md
> +    2. **Yes, I'm sure**: Button for confirm deletion of object.
```suggestion
    2. **Yes, I'm sure**: Button for confirming the deletion of the object.
```

2023-11-08 13:42 UTC, Jeremy-Prior commented on docs/src/administrator/manual/django-change-data.md
> +    3. **No, take me back**: Button to cancel deletion of the object.
```suggestion
    3. **No, take me back**: Button to cancel the deletion of the object.
```

2023-11-08 13:42 UTC, Jeremy-Prior commented on docs/src/administrator/manual/django-change-data.md
> +3. **Save and add another**: Save current record, then redirect to a new page to add a new record.
```suggestion
3. **Save and add another**: Save the current record, then redirect administrators to a new page to add a new record.
```

2023-11-08 13:42 UTC, Jeremy-Prior commented on docs/src/administrator/manual/django-change-data.md
> +4. **Save and continue editing**: Save current record while still showing current record.
```suggestion
4. **Save and continue editing**: Save the current record while still showing the current record.
```

2023-11-08 13:42 UTC, Jeremy-Prior commented on docs/src/administrator/manual/django-change-data.md
> +5. **Save**: Save current record, then redirect to Django Admin Table/record list.
```suggestion
5. **Save**: Save the current record, then redirect administrators to the Django Admin Table/record list.
```

2023-11-08 13:42 UTC, Jeremy-Prior commented on docs/src/administrator/manual/django-change-data.md
> +6. **History**: Button to see actions applied to current record.
```suggestion
6. **History**: Button to see actions applied to the current record.
```

2023-11-08 13:42 UTC, Jeremy-Prior commented on docs/src/administrator/manual/django-change-data.md
> +The other options(`History`, `Delete`, `Save and add another`, `Save and continue editing`, `Save`) work same as they are working for the other objects.
```suggestion
The other options(`History`, `Delete`, `Save and add another`, `Save and continue editing`, `Save`) work same as they do for the other objects.
```

2023-11-08 13:42 UTC, Jeremy-Prior commented on docs/src/administrator/manual/django-change-data.md
> +1. **History**: Button to see actions applied to current record.
```suggestion
1. **History**: Button to see actions applied to the current record.
```

2023-11-08 13:42 UTC, Jeremy-Prior commented on docs/src/administrator/manual/django-change-data.md
> +6. **Search Permissions**: The administrator can search for permissions using the search functionality.
Where is the associated screenshot?

2023-11-08 13:42 UTC, Jeremy-Prior commented on docs/src/administrator/manual/django-change-data.md
> +6. **Search Permissions**: The administrator can search for permissions using the search functionality.
```suggestion
### Change User Permission

1.  **Checkbox**: The administrator can grant permissions to a user by checking the checkbox.

2.  **Arrows**: The administrator can assign or unassign a group (or groups) to the user by selecting and using these arrows.

3. **Choose All**: The administrator can assign all available groups to the user.

4. **Remove All**: The administrator can unassign all groups from the user.

5. **Permissions**: The administrator can assign or unassign permissions to the user using this table.

6. **Search Permissions**: The administrator can search for permissions using the search functionality.
```

2023-11-08 13:42 UTC, Jeremy-Prior commented on docs/src/administrator/manual/django-change-data.md
> +5. **Save**: Save current record, then redirect to Django Admin Table/record list.
Image does not match text

2023-11-08 13:42 UTC, Jeremy-Prior commented on docs/src/administrator/manual/django-change-data.md
> +5. **Save**: Save current record, then redirect to Django Admin Table/record list.
```suggestion
1. **Dates**: The administrator can edit the last login date-time and date joined date-time of a user from this section.

2. **User**: The administrator can edit a user's details.

3. **Delete**: The administrator can delete the user by clicking on this button. The popup will open for the confirmation to delete the user.

4. **Save and add another**: Save the current record, then redirect administrators to a new page to add a new record.

5. **Save and continue editing**: Save the current record while still showing the current record.

6. **Save**: Save the current record, then redirect administrators to the Django Admin Table/record list.
```

2023-11-08 13:42 UTC, Jeremy-Prior commented on docs/src/administrator/manual/django-table.md
> +1. **Add button**: Clicking on this button will allow user to add a new record in the table. Clicking on [add](django-add-data.md) will navigate you to add data record documentation.
```suggestion
1. **Add button**: Clicking on this button will allow administrators to add a new record in the table. Click [here](django-add-data.md) to navigate to add data record documentation.
```

2023-11-08 13:42 UTC, Jeremy-Prior commented on docs/src/administrator/manual/django-table.md
> +4. **Action**: Users can choose the action from this dropdown and perform it on a selected object.
```suggestion
4. **Action**: Administrators can choose the action from this dropdown and perform it on a selected object.
```

2023-11-08 13:42 UTC, Jeremy-Prior commented on docs/src/administrator/manual/django-table.md
> +5. **Go**: Clicking on this button will allow users to perform the selected option on the selected object.
```suggestion
5. **Go**: Clicking on this button will allow administrators to perform the selected option on the selected object.
```

2023-11-08 13:42 UTC, Jeremy-Prior commented on docs/src/administrator/manual/django-table.md
> +6. **Objects**: Available objects containing records. Users can see the details of the object by clicking on the link.
```suggestion
6. **Objects**: Available objects containing records. Administrators can see the details of the object by clicking on the link.
```

2023-11-08 13:42 UTC, Jeremy-Prior commented on docs/src/administrator/manual/django-table.md
> +1. **Toggle sorting**: Clicking on this icon will allow users to toggle data.
```suggestion
1. **Toggle sorting**: Clicking on this icon will allow administrators to toggle the display order.
```

2023-11-08 13:42 UTC, Jeremy-Prior commented on docs/src/administrator/manual/django-table.md
> +2. **Add Group**: Clicking on the `ADD GROUP` button will allow users to add a new group. Click on [add group](django-add-data.md) to see detailed documentation about adding a new group.
```suggestion
2. **Add Group**: Clicking on the `ADD GROUP` button will allow administrators to add a new group. Click [here](django-add-data.md) to see detailed documentation about adding a new group.
```

2023-11-08 13:42 UTC, Jeremy-Prior commented on docs/src/administrator/manual/django-table.md
> +3. **Edit Record**: Clicking on the object will allow users to change/edit the particular record. Click on [change group](django-change-data.md) to see detailed documentation about editing a group.
```suggestion
3. **Edit Record**: Clicking on the object will allow administrators to change/edit the particular record. Click [here](django-change-data.md) to see detailed documentation about editing a group.
```

2023-11-08 13:42 UTC, Jeremy-Prior commented on docs/src/administrator/manual/django-table.md
> +User table within the Django Admin interface allows administrator to manage user-related tasks efficiently.
```suggestion
User table within the Django Admin interface that allows administrators to manage user-related tasks efficiently.
```

2023-11-08 13:42 UTC, Jeremy-Prior commented on docs/src/administrator/manual/django-table.md
> +1. **Add User**: Clicking on `ADD USER` button allows administrator to add a new user. Click on [add user](django-add-data.md) to see detailed documentation on adding a new user.
```suggestion
1. **Add User**: Clicking on `ADD USER` button allows administrators to add a new user. Click [here](django-add-data.md) to see detailed documentation on adding a new user.
```

2023-11-08 13:42 UTC, Jeremy-Prior commented on docs/src/administrator/manual/django-table.md
> +    1. **Clear All Filters**: Clicking on `clear all filters` allows administrator to clear all the filters.
```suggestion
    1. **Clear All Filters**: Clicking on `clear all filters` allows administrators to clear all the filters.
```

2023-11-08 13:42 UTC, Jeremy-Prior commented on docs/src/administrator/manual/django-table.md
> +3. **Search Functionality**: The administrator can search the records usign the search functionality.
```suggestion
3. **Search Functionality**: The administrator can search the records using the search functionality.
```

2023-11-08 13:42 UTC, Jeremy-Prior commented on docs/src/administrator/manual/django-table.md
> +5. **Edit User**: Clicking on the object allows the administrator to change or edit the particular record. Click on [change user](django-change-data.md) to see detailed documentation on editing a use
```suggestion
5. **Edit User**: Clicking on the object allows the administrator to change or edit the particular record. Click [here](django-change-data.md) to see detailed documentation on editing a user.
```

2023-11-09 12:14 UTC, ketankartoza commented on docs/src/administrator/manual/django-add-data.md
> +6. **Choose File**: Choose profle picture for the user.
I have changed the order.

2023-11-10 07:31 UTC, Jeremy-Prior approved these changes
LGTM

2023-11-10 07:35 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 53 sec

2023-11-10 10:00 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 41 sec

2023-11-10 10:23 UTC, ketankartoza commented
@dimasciput  I have rebased this PR please merge this PR. Thanks!

2023-11-12 23:17 UTC, merged

2023-11-12 23:22 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 45 sec