Updated testing docs
kartoza/sawps pull request #1544
Opened 2023-11-06 16:06 UTC by osundwajeff

Updated testing section in the docs

2023-11-07 11:54 UTC, Jeremy-Prior requested changes

2023-11-07 11:54 UTC, Jeremy-Prior commented on docs/src/developer/guide/testing.md
> +To install playwright browsers and OS secific depndencies:
```suggestion
To install playwright browsers and OS specific dependencies:
```

2023-11-07 11:54 UTC, Jeremy-Prior commented on docs/src/developer/guide/testing.md
> +### Continuous intergration testing
```suggestion
### Continuous integration testing
```

2023-11-07 12:09 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 19 sec

2023-11-08 13:19 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 27 sec

2023-11-09 08:03 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 16 min

2023-11-10 07:32 UTC, Jeremy-Prior approved these changes
Docs LGTM

2023-11-12 23:17 UTC, merged

2023-11-12 23:24 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 50 sec