Fix Age group bar chart for unspecified data.
kartoza/sawps pull request #1551
Opened 2023-11-07 07:45 UTC by zamuzakki

This is PR for #1408 
**The actual data**
[cheetah.json](https://github.com/kartoza/sawps/files/13277079/cheetah.json)

**The charts**
[Kazam_screencast_00048.webm](https://github.com/kartoza/sawps/assets/7352963/f9989476-8cce-4fdc-b1e0-4fa29bf3c50b)
![Population per age group for Cheetah(1)](https://github.com/kartoza/sawps/assets/7352963/36fa8c65-30c5-4fe9-8d0f-64ac80c8e82c)

2023-11-07 07:58 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 12 min

2023-11-07 08:24 UTC, dimasciput requested changes

2023-11-07 08:24 UTC, dimasciput commented on django_project/frontend/src/containers/MainPage/Metrics/AgeGroupBarChart.tsx
> +  //
@zamuzakki please just remove the lines if not used anymore.

2023-11-08 01:51 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 8 min 2 sec

2023-11-09 01:40 UTC, dimasciput approved these changes

2023-11-09 01:41 UTC, merged

2023-11-09 01:51 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 9 min 27 sec