Documentation for province report
kartoza/sawps pull request #1573
Opened 2023-11-08 15:54 UTC by ketankartoza

2023-11-08 15:57 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 36 sec

2023-11-09 12:36 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 31 sec

2023-11-10 10:11 UTC, Jeremy-Prior requested changes

2023-11-10 10:11 UTC, Jeremy-Prior commented on docs/src/user/manual/explore/reports.md
new changes look good, but I missed the use of "your" and "you" throughout this doc. Please change those to be "users", "the user", "their", etc.

2023-11-10 12:14 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 44 sec

2023-11-10 17:53 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 30 sec

2023-11-10 17:54 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 24 sec

2023-11-13 12:04 UTC, Jeremy-Prior approved these changes
LGTM

2023-11-14 01:38 UTC, merged

2023-11-14 01:45 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 6 min 48 sec