Update filter documentation
kartoza/sawps pull request #1641
Opened 2023-11-16 07:34 UTC by ketankartoza

This PR is for issue #1640

2023-11-16 13:04 UTC, ketankartoza commented
@Jeremy-Prior Please review.

2023-11-17 06:34 UTC, Jeremy-Prior requested changes

2023-11-17 06:34 UTC, Jeremy-Prior commented on docs/src/user/manual/explore/filters.md
> +* **Filter Description:** This filter allows users to search places.
```suggestion
* **Filter Description:** This filter allows users to search for places.
```

2023-11-17 06:34 UTC, Jeremy-Prior commented on docs/src/user/manual/explore/filters.md
> +* **Usage:** Click on the search place to search the places.
```suggestion
* **Usage:** Click on the search place field and type letters to search for places.
```

2023-11-17 06:34 UTC, Jeremy-Prior commented on docs/src/user/manual/explore/filters.md
> +1. **Search place:** Click on the search place to search the places and filter.
```suggestion
1. **Search place:** Click on the search place to filter places.
```

2023-11-17 06:34 UTC, Jeremy-Prior commented on docs/src/user/manual/explore/filters.md
> +* **Permission:** `Can view property filter` permission must be added to the group on the admin page,
```suggestion
* **Permission:** The `can view property filter` permission must be added to the group on the admin page, 
```

2023-11-17 06:34 UTC, Jeremy-Prior commented on docs/src/user/manual/explore/filters.md
> +to make the user group e.g. `National data scientist` able to see the property filter.
```suggestion
to allow the user group (e.g. `National data scientist`) to see the property filter.
```

2023-11-17 06:34 UTC, Jeremy-Prior commented on docs/src/user/manual/explore/filters.md
> +1. **Select All:** `Select All` select all the properties.
```suggestion
1. **Select All:** `Select All` of the properties.
```

2023-11-17 06:34 UTC, Jeremy-Prior commented on docs/src/user/manual/explore/filters.md
> +#### Report Type Filter
```suggestion
8. **Clear All**: Click on the `Clear All` button to clear all the filters.

#### Report Type Filter
```

2023-11-17 06:34 UTC, Jeremy-Prior commented on docs/src/user/manual/explore/filters.md
>  ## Summary
```suggestion
1. **Report type:** The Report Type Filter is a multi-select filter that enables users to filter data based on specific report types or view data of all the report types. With this filter, users can easily narrow down their dataset to view data associated with a particular report type.

## Summary
```

2023-11-17 06:34 UTC, Jeremy-Prior commented on docs/src/user/manual/explore/filters.md
> +The filter side panel provides a robust toolset for users to refine and explore their datasets effectively. Whether it's searching for specific places, species, or filtering by activities, organisati
```suggestion
The filter side panel provides a robust toolset for users to refine and explore their datasets effectively. Whether it's searching for specific places, species, or filtering by activities, organisations, properties, years, or spatial criteria, this comprehensive manual ensures users can seamlessly navigate and utilize the filtering functionalities for a more tailored data analysis experience.
```

2023-11-17 07:54 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 32 sec

2023-11-17 07:56 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 47 sec

2023-11-20 05:44 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 32 sec

2023-11-21 12:36 UTC, ketankartoza commented
@Jeremy-Prior Please review.

2023-11-21 12:38 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 5 sec

2023-11-22 13:25 UTC, Jeremy-Prior requested changes

2023-11-22 13:25 UTC, Jeremy-Prior commented on docs/src/user/manual/explore/filters.md
> +The filter side panel provides a robust toolset for users to refine and explore their datasets effectively. Whether it's searching for specific places, species, or filtering by activities, organisati
```suggestion
The filter side panel provides a robust toolset for users to refine and explore their datasets effectively. Whether it's searching for specific places, species, or filtering by activities, organisations, properties, years, or spatial criteria, this comprehensive manual ensures users can seamlessly navigate and utilise the filtering functionalities for a more tailored data analysis experience.
```

2023-11-28 07:07 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 23 sec

2023-11-29 01:50 UTC, merged

2023-11-29 01:53 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 6 sec