Documentation for Taxon table
kartoza/sawps pull request #1645
Opened 2023-11-16 13:03 UTC by ketankartoza

This PR is for issue #1642

2023-11-16 13:06 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 0 sec

2023-11-16 13:17 UTC, ketankartoza commented
@Jeremy-Prior Please review. Thanks!

2023-11-16 13:31 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 15 sec

2023-11-17 07:01 UTC, Jeremy-Prior requested changes

2023-11-17 07:50 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 27 sec

2023-11-17 07:52 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 54 sec

2023-11-22 10:20 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 20 sec

2023-11-22 10:21 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 49 sec

2023-11-22 13:28 UTC, Jeremy-Prior requested changes

2023-11-22 13:28 UTC, Jeremy-Prior commented on docs/src/administrator/manual/django-table.md
> +2. **Search Functionality**: Administrators can utilize the search functionality to find specific taxonomic records.
```suggestion
2. **Search Functionality**: Administrators can utilise the search functionality to find specific taxonomic records.
```

2023-11-22 13:37 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 52 sec

2023-11-22 13:47 UTC, Jeremy-Prior approved these changes
LGTM

2023-11-23 05:52 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 22 sec

2023-11-28 06:43 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 51 sec

2023-11-29 01:52 UTC, dimasciput approved these changes

2023-11-29 01:52 UTC, merged

2023-11-29 02:01 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 38 sec