Update user role documentation
kartoza/sawps pull request #1658
Opened 2023-11-17 11:46 UTC by ketankartoza

This PR is for the issue #1657

2023-11-17 11:48 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 39 sec

2023-11-22 13:35 UTC, Jeremy-Prior requested changes

2023-11-22 13:35 UTC, Jeremy-Prior commented on docs/src/user/manual/user-roles.md
> +        1. **Organisation member page**: Can only add organisation members if instated as a manager of an organisation or their organization.
```suggestion
        1. **Organisation member page**: Can only add organisation members if instated as a manager of an organisation or their organisation.
```

2023-11-22 13:47 UTC, Jeremy-Prior approved these changes
LGTM

2023-11-28 07:16 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 26 sec

2023-11-29 02:00 UTC, dimasciput approved these changes

2023-11-29 02:00 UTC, merged

2023-11-29 02:24 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 22 sec