Update map doc
kartoza/sawps pull request #1671
Opened 2023-11-20 13:41 UTC by ketankartoza

This PR is for the map documentation update.

2023-11-20 13:43 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 37 sec

2023-11-22 13:39 UTC, Jeremy-Prior requested changes

2023-11-22 13:39 UTC, Jeremy-Prior commented on docs/src/user/manual/explore/map.md
> +- **Compass Icon**: The `Compass Icon` serves as a visual guide within the map view, enhancing the user's ability to explore a 3D representation of the environment. Represented by a compass symbol, t
```suggestion
- **Compass Icon**: The `Compass Icon` serves as a visual guide within the map view, enhancing the user's ability to explore a 3D representation of the environment. Represented by a compass symbol, this icon provides users with a quick reference to the cardinal directions, facilitating orientation while navigating the 3D map. The Compass Icon dynamically adjusts its orientation based on the user's movements, consistently pointing toward Geographic North. Users can interact with the icon to reset the map orientation to its default north-facing position
```

2023-11-22 13:47 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 57 sec

2023-11-22 13:47 UTC, Jeremy-Prior approved these changes
LGTM

2023-11-27 08:31 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 23 sec

2023-11-28 06:54 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 28 sec

2023-11-29 02:06 UTC, merged

2023-11-29 02:26 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 30 sec