Feature/1654 province filter
kartoza/sawps pull request #1720
Opened 2023-11-24 07:01 UTC by zamuzakki

This is PR for #1654 
[Kazam_screencast_00058.webm](https://github.com/kartoza/sawps/assets/7352963/f2b76e4c-7245-4485-9a74-dfccdbd467b6)

2023-11-24 07:15 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 8 min 31 sec

2023-11-24 07:18 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 30 sec

2023-11-24 07:52 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 8 min 22 sec

2023-11-24 08:57 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 19 sec

2023-11-24 09:20 UTC, danangmassandy requested changes

2023-11-24 09:20 UTC, danangmassandy commented on django_project/frontend/src/containers/MainPage/Metrics/index.scss
> +.trends-left-line-chart {
perhaps, let's move this class to index.scss in Trends?

2023-11-24 09:20 UTC, danangmassandy commented on django_project/frontend/api_views/statistical.py
> +            print(PROPERTY_TREND in json_dict)
please remove this print debug

2023-11-26 01:47 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 21 sec

2023-11-27 04:02 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 48 sec

2023-11-28 04:53 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 8 min 9 sec

2023-11-29 01:50 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 44 sec

2023-11-29 02:06 UTC, dimasciput approved these changes

2023-11-29 02:07 UTC, merged

2023-11-29 02:29 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 26 sec