Add guide for fixture
kartoza/sawps pull request #1729
Opened 2023-11-24 14:14 UTC by ketankartoza

This PR is for issue #1715

2023-11-28 12:24 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 3 min 3 sec

2023-11-29 09:04 UTC, Jeremy-Prior requested changes
Minor changes

2023-11-29 09:04 UTC, Jeremy-Prior commented on docs/src/developer/guide/templates/pull-request-template.md
> +- Add screenshots which claryfies the implemented feature, fixed bug etc.
```suggestion
- Add screenshots which clarifies the implemented feature, fixed bug etc.
```

2023-11-29 09:04 UTC, Jeremy-Prior commented on docs/src/developer/guide/templates/pull-request-template.md
> +# Pull Request
```suggestion
# Pull Request Template

## Make Pull Request
```

2023-11-29 09:04 UTC, Jeremy-Prior commented on docs/src/developer/guide/templates/pull-request-template.md
> +- Push the code on the GitHub.
```suggestion
- Push the code on GitHub.
```

2023-11-29 09:54 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 8 min 9 sec

2023-11-29 12:38 UTC, Jeremy-Prior commented
Not comfortable merging as I'm not sure what is causing the django test to fail.

@dimasciput please review when possible.

2023-12-01 03:58 UTC, dimasciput approved these changes

2023-12-01 03:58 UTC, merged

2023-12-01 04:00 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 17 sec