Added more content in map doc
kartoza/sawps pull request #1734
Opened 2023-11-27 11:49 UTC by ketankartoza

This PR is for the issue #1703

@Jeremy-Prior  Please do not review this PR now, this PR relies on other PR I am creating this PR as a draft for now.

2023-11-27 11:52 UTC, ketankartoza commented
@LunaAsefaw, I am not describing the year filter in this documentation because all the filters with the map are defined in the filter doc.

2023-11-29 07:21 UTC, ketankartoza commented
@Jeremy-Prior  this PR is ready for review now.

2023-11-29 08:20 UTC, Jeremy-Prior requested changes
1 minor change

2023-11-29 08:20 UTC, Jeremy-Prior commented on docs/src/user/manual/explore/map.md
> +3. **Dots**: Upon landing, users are greeted with a visual representation of property locations in the form of dots, providing an immediate overview of the geographical distribution of properties (un
```suggestion
3. **Points**: Upon landing on the page, users are greeted with a visual representation of property locations in the form of points, providing an immediate overview of the geographical distribution of properties (unless the user is designated as a data consumer).
```

2023-11-29 09:13 UTC, Jeremy-Prior approved these changes
LGTM

2023-11-29 09:13 UTC, merged

2023-11-29 09:26 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 8 min 20 sec

2023-11-29 09:28 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 33 sec