Update images and doc user manual
kartoza/sawps pull request #1786
Opened 2023-11-30 14:28 UTC by ketankartoza

This PR is for issue #1681 

@LunaAsefaw in task one the image is already updated.

2023-11-30 14:31 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 37 sec

2023-12-05 08:25 UTC, Jeremy-Prior requested changes

2023-12-05 08:25 UTC, Jeremy-Prior commented on docs/src/user/manual/explore/filters.md
> +1. **Province Filter:** In the province filter, all provinces are initially selected as the default setting. Users have the freedom to hand-pick a provice of their choice.
```suggestion
1. **Province Filter:** In the province filter, all provinces are initially selected as the default setting. Users have the freedom to hand-pick a province of their choice.
```

2023-12-05 09:45 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 43 sec

2023-12-05 12:15 UTC, Jeremy-Prior approved these changes
LGTM

2023-12-05 12:16 UTC, merged