Fix trends page issues
kartoza/sawps pull request #1792
Opened 2023-12-01 07:11 UTC by danangmassandy

This PR is for below tickets (the preview are in each ticket):

- #1765
- #1751 
- #1740
- #1673
- Fix layout in national trend
- Fix population trends charts that grows outside chart container

2023-12-01 07:18 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 26 sec

2023-12-01 07:30 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 50 sec

2023-12-04 05:25 UTC, dimasciput requested changes

2023-12-04 05:25 UTC, dimasciput commented on django_project/frontend/src/utils/Helpers.ts
> +export function isDataConsumer(userInfo: UserInfo) {
@danangmassandy let's use permission instead. See here https://github.com/kartoza/sawps/pull/1788#pullrequestreview-1761621040

2023-12-04 07:39 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 8 min 40 sec

2023-12-04 08:31 UTC, danangmassandy commented on django_project/frontend/src/utils/Helpers.ts
> +  console.log('dateTime ', dateTime)
I've removed the console log

2023-12-04 09:18 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 9 min 32 sec

2023-12-04 10:16 UTC, merged