Fix upload data button permission
kartoza/sawps pull request #1793
Opened 2023-12-01 11:37 UTC by danangmassandy

This is for #1772.

Upload Data link is disabled for Data Consumer/Data Scientiest:
![image](https://github.com/kartoza/sawps/assets/5819076/ac293f18-dea0-41ca-9e03-517a5e94784c)

There is also validation when accessing the /upload or /map?tab=4 to raise permission denied if this URL is accessed by Data Consumer/Data Scientiest.
I also hide the actions column in Species Report:
![image](https://github.com/kartoza/sawps/assets/5819076/6b2645f6-b0cb-4caa-b2d5-56a6058ca227)

2023-12-01 11:46 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 8 min 10 sec

2023-12-04 05:28 UTC, dimasciput requested changes

2023-12-04 14:56 UTC, danangmassandy commented on django_project/frontend/src/utils/Helpers.ts
> +export function isDataScientiest(userInfo: UserInfo) {
updated

2023-12-05 02:36 UTC, dimasciput approved these changes

2023-12-05 02:37 UTC, dimasciput commented
@danangmassandy please fix the conflicts

2023-12-05 03:13 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 8 min 37 sec

2023-12-05 03:20 UTC, danangmassandy commented
I'll merge this PR, the test that was failed is playwright test.

2023-12-05 03:20 UTC, merged

2023-12-05 03:23 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 54 sec