Documentation for the statistical model
kartoza/sawps pull request #1829
Opened 2023-12-08 13:02 UTC by ketankartoza

This PR is for issue #1825

2023-12-08 13:05 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 32 sec

2023-12-08 13:16 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 51 sec

2023-12-11 06:59 UTC, Jeremy-Prior requested changes

2023-12-11 06:59 UTC, Jeremy-Prior commented on docs/src/administrator/manual/django-change-data.md
> +3. **Delete Checkbox**: Check mark the checkbox to delete the associat statistical output type.
```suggestion
3. **Delete Checkbox**: Check mark the checkbox to delete the associated statistical output type.
```

2023-12-11 07:27 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 17 sec

2023-12-11 12:08 UTC, Jeremy-Prior approved these changes
LGTM

2023-12-11 12:12 UTC, merged

2023-12-11 12:14 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 19 sec