Add re upload section
kartoza/sawps pull request #1997
Opened 2024-02-27 07:48 UTC by ketankartoza

This PR is for issue #1948 

The extra 1 hour is taken to complete this task due to testing and reporting the bug causing the issue while uploading the file. 
![image](https://github.com/kartoza/sawps/assets/138113337/0fcff9e5-2b65-46b7-b2f8-620e4a77fbc7)

2024-02-27 07:50 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 55 sec

2024-02-28 06:53 UTC, Jeremy-Prior requested changes

2024-02-28 06:53 UTC, Jeremy-Prior commented on docs/src/user/manual/data-upload/update-data.md
> +context_id: BYbnmQvaLxzHsfjUtsaAFn
This needs to be unique, you can't copy the context ID from another file (this was copied from reports.md). There is a script to generate new uuids (`create-uuid.py`)
```suggestion
context_id: 86E2FetEjDbkA6t7ET8efs
```

2024-02-29 06:58 UTC, Jeremy-Prior approved these changes
LGTM

2024-02-29 06:58 UTC, merged

2024-02-29 07:01 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 3 min 5 sec