patch: update organisation users
kartoza/sawps pull request #649
Opened 2023-07-13 09:04 UTC by DONOTFORGET-BYTE

2023-07-13 09:35 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 19 min

2023-07-13 09:36 UTC, DONOTFORGET-BYTE commented
@dimasciput @danangmassandy I made a few changes Amy spotted a few issues

2023-07-13 09:55 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 19 min

2023-07-13 10:38 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 19 min

2023-07-13 11:04 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 10 min

2023-07-13 13:23 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 20 min

2023-07-14 02:12 UTC, dimasciput requested changes
Please clean up your PR, it currently displays old commits from a different PR.

2023-07-14 02:12 UTC, dimasciput commented on django_project/sawps/views.py
> +                ['amy@kartoza.com'],
don't put the email directly here. Instead, use the variable from the Django settings 

https://github.com/kartoza/sawps/blob/eb33c7ff255d8f7dc4a974d79f88c2525bf4c6f6/django_project/core/settings/contrib.py#L106

2023-07-14 02:12 UTC, dimasciput commented on django_project/sawps/views.py
>                  print('Failed to send email:', str(e))
remove this

2023-07-14 06:02 UTC, DONOTFORGET-BYTE commented
@dimasciput I have used the support email from contrib.py

2023-07-14 06:13 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 12 min

2023-07-14 06:19 UTC, dimasciput commented
![Screenshot 2023-07-14 at 1 18 56 PM](https://github.com/kartoza/sawps/assets/1979569/419bd209-89e7-4297-9ba2-b62357265622)

@DONOTFORGET-BYTE your PR still displays old commits

2023-07-14 08:06 UTC, closed without merging

2023-07-14 08:07 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 56 sec