Feature data dashboard
kartoza/sawps pull request #685
Opened 2023-07-21 05:50 UTC by ketankartoza

This PR is for Line Chart #659

Before :
<img width="1662" alt="Screenshot 2023-07-21 at 11 18 32 AM" src="https://github.com/kartoza/sawps/assets/138113337/343c0197-e25a-49a6-8ad7-255f68b9831b">
After:
<img width="1679" alt="Screenshot 2023-07-21 at 11 20 19 AM" src="https://github.com/kartoza/sawps/assets/138113337/9b914a12-0a84-47ac-9e25-5c5e15725696">

2023-07-21 06:03 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 7 min 55 sec

2023-07-21 06:12 UTC, dimasciput requested changes

2023-07-21 06:12 UTC, dimasciput commented on django_project/frontend/serializers/metrics.py
> +            'specie_name',
should be `species_name`

2023-07-21 06:12 UTC, dimasciput commented on django_project/frontend/serializers/metrics.py
> +            'specie_colour',
`species_colour`

2023-07-21 06:12 UTC, dimasciput commented on django_project/frontend/serializers/metrics.py
> +        annual_populations = AnnualPopulation.objects.filter(
@ketankartoza why not use single query?

``` 
annual_populations = AnnualPopulation.objects.filter(
        owned_species__taxon=obj,
        month__name__in=months.split(',') if months else F('month__name')
    ).values('month').annotate(month_total=Sum('total'))
```

2023-07-21 06:12 UTC, dimasciput commented on django_project/frontend/src/containers/MainPage/Metrics/SpeciesLineChart.tsx
> +    const [selectedProperty, setSelectedProperty] = useState<PropertyInterface>(propertyList?.[0])
Why do you need both selectedPropertyId and selectedProperty? Could you derive selectedProperty from selectedPropertyId and propertyList?

2023-07-21 07:46 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 13 min

2023-07-21 10:37 UTC, ketankartoza commented
@dimasciput I have done with the requested changes please review and merge

2023-07-21 10:51 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 12 min

2023-07-22 05:28 UTC, dimasciput commented
@ketankartoza please fix the lint errors

2023-07-24 05:40 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 11 min

2023-07-24 05:41 UTC, ketankartoza commented
> @ketankartoza please fix the lint errors

@dimasciput I have fixed the lint errors.

2023-07-24 05:56 UTC, dimasciput commented
@ketankartoza please fix the broken test

2023-07-24 06:09 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 11 min

2023-07-24 06:09 UTC, ketankartoza commented
> @ketankartoza please fix the broken test



> @ketankartoza please fix the broken test

@dimasciput test case for this API is working fine, the previous test cases are failing.

2023-07-24 06:24 UTC, dimasciput commented
@ketankartoza the build has failed : https://github.com/kartoza/sawps/actions/runs/5641209652/job/15278916527?pr=685. Could you please fix the issue?

2023-07-24 08:21 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 15 min

2023-07-24 12:15 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 17 min

2023-07-25 01:19 UTC, dimasciput approved these changes

2023-07-25 01:19 UTC, merged

2023-07-25 01:34 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 14 min