Feature reminders page
kartoza/sawps pull request #686
Opened 2023-07-21 06:37 UTC by DONOTFORGET-BYTE

2023-07-21 06:49 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 11 min

2023-07-21 07:01 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 11 min

2023-07-21 07:21 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 19 min

2023-07-21 07:32 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 11 min

2023-07-21 08:05 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 19 min

2023-07-21 08:25 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 19 min

2023-07-21 08:46 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 20 min

2023-07-21 09:07 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 21 min

2023-07-21 10:26 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 18 min

2023-07-21 10:38 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 11 min

2023-07-21 11:09 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 18 min

2023-07-21 11:27 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 17 min

2023-07-21 21:01 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 17 min

2023-07-21 21:16 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 15 min

2023-07-21 21:55 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 14 min

2023-07-22 05:29 UTC, dimasciput requested changes

2023-07-22 05:29 UTC, dimasciput commented on django_project/stakeholder/views.py
> +def create_return_results(reminders):
@DONOTFORGET-BYTE Please use a serializer to achieve this.

2023-07-23 22:28 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 16 min

2023-07-23 22:42 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 14 min

2023-07-23 22:58 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 15 min

2023-07-23 23:13 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 14 min

2023-07-23 23:28 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 15 min

2023-07-24 05:54 UTC, dimasciput requested changes

2023-07-24 05:54 UTC, dimasciput commented on django_project/stakeholder/views.py
> +    local_timezone = pytz.timezone('Africa/Johannesburg')
@DONOTFORGET-BYTE why do you convert to the South Africa timezone only? What if the user is from a different region? Perhaps you can handle the conversion on the frontend, as the browser will be aware of the user's timezone.

2023-07-24 05:57 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 16 min

2023-07-24 07:03 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 16 min

2023-07-24 07:18 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 15 min

2023-07-24 07:34 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 16 min

2023-07-24 07:50 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 15 min

2023-07-24 13:14 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 15 min

2023-07-24 14:22 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 15 min

2023-07-24 14:51 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 16 min

2023-07-24 15:23 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 15 min

2023-07-25 03:08 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 15 min

2023-07-25 04:05 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 15 min

2023-07-25 04:21 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 15 min

2023-07-25 04:50 UTC, dimasciput approved these changes

2023-07-25 04:50 UTC, merged

2023-07-25 05:06 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 15 min