Feature notifications page
kartoza/sawps pull request #707
Opened 2023-07-25 13:07 UTC by DONOTFORGET-BYTE

2023-07-25 13:43 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 23 min

2023-07-26 01:59 UTC, dimasciput requested changes

2023-07-26 01:59 UTC, dimasciput commented on django_project/stakeholder/test_view.py
> +    # @patch('stakeholder.views.convert_reminder_dates')
Please remove commented codes

2023-07-26 06:53 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 23 min

2023-07-26 07:16 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 22 min

2023-07-26 08:21 UTC, dimasciput approved these changes

2023-07-26 08:22 UTC, merged

2023-07-26 08:32 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 21 min

2023-07-26 08:53 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 21 min