Delete edit reminders notifications
kartoza/sawps pull request #709
Opened 2023-07-25 21:46 UTC by DONOTFORGET-BYTE

2023-07-25 22:07 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 21 min

2023-07-26 09:15 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 21 min

2023-07-26 10:18 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 21 min

2023-07-27 00:44 UTC, dimasciput requested changes

2023-07-27 00:44 UTC, dimasciput commented on django_project/frontend/templates/notifications.html
> +        color: #70B276;
@DONOTFORGET-BYTE please use css variable instead.

2023-07-27 00:48 UTC, dimasciput commented on django_project/frontend/templates/notifications.html
> +        color: #70B276;
for example

```
:root {
  --main-green: #70B276;
}

.pagination a.page-link {
  color: var(--main-green);
}
```

2023-07-27 05:08 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 19 min

2023-07-27 05:29 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 20 min

2023-07-27 05:50 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 21 min

2023-07-27 06:12 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 21 min

2023-07-27 06:34 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 21 min

2023-07-27 06:57 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 23 min

2023-07-27 07:15 UTC, dimasciput approved these changes

2023-07-27 07:15 UTC, merged

2023-07-27 07:20 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 22 min

2023-07-27 07:42 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 22 min

2023-07-27 08:04 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 21 min

2023-07-27 09:25 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 24 min