Fix filter UI added Property field
kartoza/sawps pull request #716
Opened 2023-07-27 12:25 UTC by ketankartoza

This PR is for Filter UI update and added Property #572 

Before : 
<img width="405" alt="Screenshot 2023-07-27 at 5 55 00 PM" src="https://github.com/kartoza/sawps/assets/138113337/0369df99-212f-491a-a358-3da9e9b12b2c">

After:
<img width="403" alt="Screenshot 2023-07-27 at 5 55 28 PM" src="https://github.com/kartoza/sawps/assets/138113337/24b98ab7-d2a9-4335-9851-be59eb1312ab">

2023-07-27 12:54 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 25 min

2023-07-27 13:56 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 21 min

2023-07-28 03:30 UTC, dimasciput requested changes

2023-07-28 03:30 UTC, dimasciput commented on django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
> +        dispatch(toggleSpecies(updatedSelectedSpecies.length > 0 ? updatedSelectedSpecies.join(',') : ''));
Please avoid repeating yourself multiple times. You can create a `useEffect` for `selectedSpecies` and then run `dispatch` within it.
```
useEffect(() => {
    dispatch(toggleSpecies(selectedSpecies.length > 0 ? selectedSpecies.join(',') : ''));
}, [selectedSpecies])
```

2023-07-28 05:27 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 20 min

2023-07-28 09:56 UTC, dimasciput approved these changes

2023-07-28 09:56 UTC, merged

2023-07-28 10:09 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 12 min