Use case fixes
kartoza/sawps pull request #732
Opened 2023-08-02 01:05 UTC by tinashechiraya

2023-08-02 01:08 UTC, tinashechiraya commented
![email_exists](https://github.com/kartoza/sawps/assets/70011086/af7eee73-0c11-45e6-a236-0e8252ee9aa2)
![email_invalid](https://github.com/kartoza/sawps/assets/70011086/ee0e3c0c-a2b9-475d-993a-8e2143640357)
![notification_on_tab](https://github.com/kartoza/sawps/assets/70011086/0d0ba1ce-b4c7-47c7-a001-4925c78d7fdf)

2023-08-02 01:14 UTC, tinashechiraya commented
![content_fills](https://github.com/kartoza/sawps/assets/70011086/08c96b14-c465-47cf-bfde-8d472084f169)
![notifications](https://github.com/kartoza/sawps/assets/70011086/3fc745dc-ab58-4f3f-bbdd-2c833b69e7bc)
now content fills on the page , compared to the current on staging site

2023-08-03 02:33 UTC, danangmassandy requested changes

2023-08-03 02:33 UTC, danangmassandy commented on django_project/stakeholder/views.py
> +def check_email_exists(request):
@tinashechiraya can this API be accessed by public or only by registered user? if this is for registered user, then please protect it by using IsAuthenticated from rest_framework.

2023-08-03 06:17 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 13 min

2023-08-03 06:29 UTC, danangmassandy approved these changes

2023-08-03 06:29 UTC, merged

2023-08-03 06:32 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 15 min

2023-08-03 06:59 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 13 min