Number of properties per population category
kartoza/sawps pull request #740
Opened 2023-08-03 09:27 UTC by ketankartoza

This Pr is for #664 

Before:
<img width="1671" alt="Screenshot 2023-08-03 at 2 55 59 PM" src="https://github.com/kartoza/sawps/assets/138113337/ea2a6e09-a457-4ad2-9cfb-d6e69cc8efae">
After:
<img width="1678" alt="Screenshot 2023-08-03 at 2 56 31 PM" src="https://github.com/kartoza/sawps/assets/138113337/16150bce-f0be-496c-bdf2-3a4d54a9a420">

2023-08-03 09:39 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 12 min

2023-08-04 01:40 UTC, dimasciput requested changes

2023-08-04 01:40 UTC, dimasciput commented on django_project/frontend/utils/metrics.py
> +def calculate_population_categories(queryset):
Hi @ketankartoza, could you please add a docstring here? It's a bit confusing to understand what the queryset is. Also, could you provide a type hint for the queryset?

2023-08-04 01:40 UTC, dimasciput commented on django_project/frontend/utils/metrics.py
> +    POPULATION_CATEGORY_DICT = {
In Python convention, uppercase names are used for constants, which don't change once assigned.

2023-08-04 01:40 UTC, dimasciput commented on django_project/frontend/api_views/metrics.py
> +class PropertiesPerPopulationCategoryAPIView(APIView):
Please add docstring here too

2023-08-04 06:58 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 1 min 22 sec

2023-08-04 11:02 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 15 min

2023-08-07 05:45 UTC, dimasciput approved these changes

2023-08-07 05:46 UTC, merged

2023-08-07 06:00 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 14 min