integration property type chart
kartoza/sawps pull request #776
Opened 2023-08-11 06:40 UTC by ketankartoza

This PR is for #766

Before : 
<img width="1669" alt="Screenshot 2023-08-11 at 12 09 56 PM" src="https://github.com/kartoza/sawps/assets/138113337/ee021c00-13bb-49dc-9b77-c4a52f78cb1e">
After:
<img width="1670" alt="Screenshot 2023-08-11 at 12 10 33 PM" src="https://github.com/kartoza/sawps/assets/138113337/be4c7731-cf31-4d6a-bb7e-2c32bf252b07">

2023-08-11 07:22 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 24 min

2023-08-15 03:38 UTC, dimasciput requested changes

2023-08-15 03:38 UTC, dimasciput commented on django_project/frontend/tests/test_metrics.py
> +            self.assertEqual(response.data[0]['total_area'], 200)
```suggestion
          """
          Test total area per property type filtered by property.
          """
          id = self.owned_species[0].property_id
          data = {'property':id}
          url = self.url
          response = self.client.get(url, data, **self.auth_headers)
          self.assertEqual(response.status_code, status.HTTP_200_OK)
          self.assertEqual(response.data[0]['total_area'], 200)
```

2023-08-15 03:38 UTC, dimasciput commented on django_project/frontend/utils/metrics.py
> +    property_ids = [query.id for query in queryset]
```suggestion
    property_ids = queryset.values_list('id', flat=True)
```

2023-08-17 07:03 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 30 min

2023-08-17 07:32 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 28 min

2023-08-17 08:01 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 28 min

2023-08-18 06:59 UTC, dimasciput approved these changes

2023-08-18 06:59 UTC, merged

2023-08-18 08:33 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 26 min