Add map styles for national
kartoza/sawps pull request #863
Opened 2023-08-22 19:19 UTC by tinashechiraya

[Screencast from 22-08-23 20:16:38.webm](https://github.com/kartoza/sawps/assets/70011086/76eccdd8-666e-42ec-bd22-d75cb42e60c3)

2023-08-22 19:20 UTC, tinashechiraya commented
Description:

Map styles for national level
1. when on national level/decision maker role ,as demonstrated in the video user cant zoom in to deeper levels like viewing properties property etc

2023-08-24 03:31 UTC, danangmassandy requested changes

2023-08-24 03:31 UTC, danangmassandy commented on django_project/frontend/utils/country_level_dark_v1.json
> +  "glyphs": "https://api.maptiler.com/fonts/{fontstack}/{range}.pbf?key={key}",
please use `key={{MAPTILER_API_KEY}}`

2023-08-24 03:31 UTC, danangmassandy commented on django_project/frontend/utils/country_level_dark_v1.json
> +    "sanbi:version": "12",
Use version sanbi:version 1 for this style.

2023-08-24 03:31 UTC, danangmassandy commented on django_project/frontend/utils/country_level_dark_v1.json
> +      "minZoom": 0,
I think let's set to minZoom: 5. This is one of the change that I need to do for importing Jeremy style.
Can also change other occurrance for minZoom: 0?
Please also apply to light theme

2023-08-24 07:22 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 26 min

2023-08-24 07:36 UTC, danangmassandy approved these changes

2023-08-24 07:37 UTC, merged

2023-08-24 07:48 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 25 min

2023-08-24 08:41 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 27 min

2023-08-24 09:08 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 26 min

2023-08-24 09:37 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 29 min

2023-08-24 11:00 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 27 min

2023-08-24 11:38 UTC, tinashechiraya commented
![national_level_map](https://github.com/kartoza/sawps/assets/70011086/74191adb-5888-42c3-81c1-5d5a055498d0)
on staging site the appearance of nation level map