National report pdf page 4
kartoza/sawps pull request #884
Opened 2023-08-28 05:40 UTC by tinashechiraya

2023-08-28 05:45 UTC, tinashechiraya commented
[national_report-21.pdf](https://github.com/kartoza/sawps/files/12450646/national_report-21.pdf)

2023-08-28 08:22 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 27 min

2023-08-28 08:50 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 27 min

2023-08-28 13:22 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 29 min

2023-08-29 09:58 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 29 min

2023-08-29 10:28 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 29 min

2023-08-31 07:38 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 29 min

2023-09-02 20:21 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 22 min

2023-09-04 00:31 UTC, tinashechiraya commented
[national_report-18.pdf](https://github.com/kartoza/sawps/files/12508355/national_report-18.pdf)

with updated styling on pdf

2023-09-04 05:03 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 21 min

2023-09-04 05:26 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 22 min

2023-09-04 05:49 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 22 min

2023-09-04 06:12 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 22 min

2023-09-04 06:38 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 25 min

2023-09-04 07:02 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 24 min

2023-09-04 07:27 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 24 min

2023-09-04 07:54 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 27 min

2023-09-04 08:19 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 25 min

2023-09-04 08:46 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 27 min

2023-09-04 13:56 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 25 min

2023-09-07 07:09 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 29 min

2023-09-08 12:19 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 27 min

2023-09-11 02:43 UTC, dimasciput requested changes

2023-09-11 02:43 UTC, dimasciput commented on django_project/frontend/tests/test_national_statistics.py
> +        response = self.client.get(url, **self.auth_headers)
Please also test  the response data

2023-09-11 02:43 UTC, dimasciput commented on django_project/frontend/tests/test_national_statistics.py
> +        self.assertEqual(response.status_code, status.HTTP_200_OK)
Add response data testing here

2023-09-11 02:43 UTC, dimasciput commented on django_project/frontend/api_views/national_statistic.py
> +        # provinces = Province.objects.all()
If not used please remove it

2023-09-11 02:43 UTC, dimasciput commented on django_project/frontend/api_views/national_statistic.py
> +        # provinces = Province.objects.all()
Please remove

2023-09-13 01:32 UTC, dimasciput approved these changes

2023-09-13 01:35 UTC, merged

2023-09-13 01:58 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 22 min