Organisations page
kartoza/sawps pull request #920
Opened 2023-08-31 13:06 UTC by tinashechiraya

[Screencast from 31-08-23 13:34:56.webm](https://github.com/kartoza/sawps/assets/70011086/2df8b381-5bae-4e8a-8ad3-27b7c8f544be)

Descriptions:
the switch organisation has been removed from the dropdown in the navigation from the header to this page
on this page user can see the list of organisations they have access to 
the user can choose the organisation they wish to set active 
clicking on an organisation that is currently active will navigate to the organisation users page

2023-09-01 02:48 UTC, dimasciput commented
@tinashechiraya selected organisatation need to be stored in database not in session anymore

2023-09-01 04:40 UTC, tinashechiraya commented
@dimasciput Yes I made a comment on that , I asked if I should proceed with making another ticket on that because changing the the active organisation from being stored in the session to the db will also affect other parts of the code so I will have to update them as well 

![2023-09-01_06-37](https://github.com/kartoza/sawps/assets/70011086/f77755d5-f7f6-4e84-9f9e-a9c7bf9105a8)

2023-09-01 05:27 UTC, dimasciput commented
@tinashechiraya thanks, can you add it here please

2023-09-01 05:37 UTC, tinashechiraya commented
@dimasciput Alright no problem

2023-09-01 06:23 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 29 min

2023-09-02 16:05 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 24 min

2023-09-02 16:31 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 25 min

2023-09-02 16:56 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 24 min

2023-09-02 17:18 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 21 min

2023-09-02 17:40 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 22 min

2023-09-02 18:02 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 21 min

2023-09-02 18:26 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 23 min

2023-09-02 18:48 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 22 min

2023-09-02 19:11 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 23 min

2023-09-02 19:35 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 24 min

2023-09-02 19:59 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 23 min

2023-09-02 21:08 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 47 min

2023-09-02 21:32 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 23 min

2023-09-02 21:56 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 24 min

2023-09-02 22:21 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 24 min

2023-09-02 22:45 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 24 min

2023-09-02 23:08 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 23 min

2023-09-03 07:05 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 25 min

2023-09-03 07:30 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 24 min

2023-09-03 07:55 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 24 min

2023-09-03 08:20 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 24 min

2023-09-03 08:44 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 24 min

2023-09-03 09:09 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 24 min

2023-09-03 09:35 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 25 min

2023-09-03 10:00 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 24 min

2023-09-03 17:37 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 25 min

2023-09-03 18:01 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 24 min

2023-09-04 00:07 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 22 min

2023-09-04 00:29 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 21 min

2023-09-04 00:36 UTC, tinashechiraya commented
@dimasciput I have now added a new field on the user profile that will store their current/active organisation .
I have also replaced all the places in the code that were using the current organisation from the session , it will now use the new utility function to fetch the current organisation from the user profile.
I have also update a few tests so they don't break

2023-09-04 01:11 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 41 min

2023-09-04 01:33 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 22 min

2023-09-04 01:56 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 23 min

2023-09-04 02:49 UTC, dimasciput requested changes

2023-09-04 02:49 UTC, dimasciput commented on django_project/frontend/api_views/map.py
> +        ) or 0
Could you remove this? Just let it returns None.

2023-09-04 02:49 UTC, dimasciput commented on django_project/stakeholder/test_view.py
> +        # request.session = {CURRENT_ORGANISATION_ID_KEY: self.organisation.id}
Please just remove all commented codes.

2023-09-04 07:35 UTC, dimasciput approved these changes

2023-09-04 07:35 UTC, merged