Update data-table
kartoza/sawps pull request #950
Opened 2023-09-08 09:36 UTC by ketankartoza

This PR is for #855

Before : 
<img width="1675" alt="Screenshot 2023-09-08 at 3 04 26 PM" src="https://github.com/kartoza/sawps/assets/138113337/abb008ae-d125-4711-bb90-a9f63b8b5618">
After:
<img width="1673" alt="Screenshot 2023-09-08 at 2 56 33 PM" src="https://github.com/kartoza/sawps/assets/138113337/f295e5f2-bda7-4570-b05b-b8565ade2155">
<img width="1666" alt="Screenshot 2023-09-08 at 2 57 34 PM" src="https://github.com/kartoza/sawps/assets/138113337/3c6d7f73-f8b0-46a0-929a-548f5d3ee167">
<img width="1676" alt="Screenshot 2023-09-08 at 2 58 41 PM" src="https://github.com/kartoza/sawps/assets/138113337/28bd6f17-50fa-4aff-b67f-2328fd204b46">

2023-09-11 02:47 UTC, dimasciput requested changes

2023-09-11 02:47 UTC, dimasciput commented on django_project/frontend/utils/data_table.py
> +def sampling_report(queryset: QuerySet, request) -> List:
Please add tests for this function

2023-09-11 02:47 UTC, dimasciput commented on django_project/frontend/utils/data_table.py
> +def activity_report(queryset: QuerySet, request) -> Dict[str, List[Dict]]:
Please add tests for this function

2023-09-11 07:22 UTC, ketankartoza commented on django_project/frontend/utils/data_table.py
> +def sampling_report(queryset: QuerySet, request) -> List:
Okay

2023-09-11 07:22 UTC, ketankartoza commented on django_project/frontend/utils/data_table.py
> +def activity_report(queryset: QuerySet, request) -> Dict[str, List[Dict]]:
Sure

2023-09-12 02:24 UTC, dimasciput requested changes

2023-09-12 02:24 UTC, dimasciput commented on django_project/frontend/utils/data_table.py
> +    Species_population_reports = []
Please follow python coding standard

2023-09-12 02:24 UTC, dimasciput commented on django_project/frontend/utils/data_table.py
> +    Property_reports = []
```suggestion
    property_reports = []
```

2023-09-13 01:36 UTC, dimasciput approved these changes

2023-09-13 01:36 UTC, merged