Fix shapefile upload
kartoza/sawps pull request #953
Opened 2023-09-11 05:13 UTC by danangmassandy

This PR is for #807 include:

- Add error message when parcel has been used by existing property
- Change the parcel query to intersects with uploaded geometry

Preview of error message:

![Screenshot_4666](https://github.com/kartoza/sawps/assets/5819076/f4f9b4d5-e12b-4244-ad64-567571d65be6)

2023-09-11 05:14 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 1 min 18 sec

2023-09-11 13:52 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 26 min

2023-09-12 02:27 UTC, dimasciput requested changes

2023-09-12 02:27 UTC, dimasciput commented on django_project/frontend/src/containers/MainPage/Upload/Uploader.tsx
> +                            _error = `Error! Parcels ${_usedParcels} have been already used by other property!`
```suggestion
                            _error = `Error! Parcels ${_usedParcels} have already been used by another property.`
```

2023-09-12 02:27 UTC, dimasciput commented on django_project/frontend/src/containers/MainPage/Upload/Uploader.tsx
> +                        let _error = `Error! Parcel ${_usedParcels} has been already used by other property!`
```suggestion
                        let _error = `Error! Parcel ${_usedParcels} has already been used by another property.`
```

2023-09-12 03:17 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 22 min

2023-09-13 01:39 UTC, dimasciput approved these changes

2023-09-13 01:39 UTC, merged

2023-09-13 02:21 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 22 min